# Generated by Django 2.2 on 2020-01-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='password1',
            field=models.CharField(max_length=60),
        ),
    ]
