# Generated by Django 2.2 on 2020-01-14 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=25)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
