# Generated by Django 2.2 on 2020-01-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='label',
            field=models.ManyToManyField(to='note.Label'),
        ),
    ]
