# Generated by Django 2.2 on 2020-01-14 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_note_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='name',
            new_name='user_id',
        ),
    ]
